version: '3.8'

services:
  backend:
    image: unittcms-backend:latest
    build:
      context: ./backend
    ports:
      - '${BACKEND_PORT}:${BACKEND_PORT}'
    environment:
      - NODE_ENV=production
      - FRONTEND_ORIGIN=${FRONTEND_ORIGIN}
      - PORT=${BACKEND_PORT}
    volumes:
      - db-data:/app/database

  frontend:
    image: unittcms-frontend:latest
    build:
      context: ./frontend
    ports:
      - '${FRONTEND_PORT}:${FRONTEND_PORT}'
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BACKEND_ORIGIN=${NEXT_PUBLIC_BACKEND_ORIGIN}
      - PORT=${FRONTEND_PORT}
    depends_on:
      - backend

volumes:
  db-data:
